# Generated by Django 3.2.2 on 2021-05-26 18:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('file', models.BinaryField()),
                ('skills', models.CharField(max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='JobOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('isActive', models.BooleanField()),
                ('creation_date', models.DateField()),
                ('dueDate', models.DateField()),
                ('description', models.CharField(max_length=5000)),
                ('bottomSalaryRange', models.IntegerField()),
                ('upperSalaryRange', models.IntegerField()),
                ('additionalBenefits', models.CharField(max_length=5000)),
                ('niceToHave', models.CharField(max_length=5000)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=512)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('secondName', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('phone', models.CharField(max_length=12, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserMeeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Projekt_zespołowy.meeting')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=512)),
                ('jobOffer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Projekt_zespołowy.joboffer')),
            ],
        ),
        migrations.CreateModel(
            name='PromisingCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Projekt_zespołowy.application')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Projekt_zespołowy.person')),
            ],
        ),
        migrations.CreateModel(
            name='PersonMeeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Projekt_zespołowy.meeting')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Projekt_zespołowy.person')),
            ],
        ),
        migrations.CreateModel(
            name='OpinionAboutCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Content', models.CharField(max_length=5000)),
                ('candidateId', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=512)),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
                ('stillWorking', models.BooleanField()),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Projekt_zespołowy.application')),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=5000)),
                ('degree', models.CharField(max_length=255)),
                ('graduationDateOrExpectedDate', models.DateField()),
                ('inProgress', models.BooleanField()),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Projekt_zespołowy.application')),
            ],
        ),
        migrations.AddField(
            model_name='application',
            name='jobOffer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Projekt_zespołowy.joboffer'),
        ),
        migrations.AddField(
            model_name='application',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Projekt_zespołowy.person'),
        ),
    ]
