# Generated by Django 3.2.2 on 2021-06-01 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projekt_zespołowy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='joboffer',
            name='requirements',
            field=models.CharField(default='brak', max_length=1000),
        ),
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='person',
            name='phone',
            field=models.CharField(max_length=12),
        ),
    ]
