# Generated by Django 3.2.3 on 2021-06-13 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Projekt_zespołowy', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opinionaboutcandidate',
            name='candidateId',
        ),
        migrations.AddField(
            model_name='opinionaboutcandidate',
            name='application',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Projekt_zespołowy.application'),
        ),
        migrations.AddField(
            model_name='opinionaboutcandidate',
            name='candidate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Projekt_zespołowy.person'),
        ),
    ]
